POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The Self 2",
    "author": "Menashe",
    "url": "https://theself.wordpress.com/",
    "likes": 120
}
###
GET http://localhost:3003/api/blogs