POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The Self 2",
    "author": "Menashe",
    "url": "https://theself.wordpress.com/",
    "likes": 120
}
###
GET http://localhost:3003/api/blogs
###
DELETE http://localhost:3003/api/blogs/628d3708117f007372438302
###
PUT http://localhost:3003/api/blogs/123
Content-Type: application/json

{
    "title": "The Self 3",
    "author": "Menashe",
    "url": "https://theself.wordpress.com/",
    "likes": 20
}